


GET http://localhost:5000/users

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "doctor_id": "34",
    "doctor_name": "Jhon",
    "email": "jhon@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "day": "Rabu",
    "time_start": "13.00",
    "time_finish": "14.00",
    "quota": "22",
    "status": "true",
    "date_range": "2022-11-22"
  }